### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by ericdrosado** [AkashSingh3031/The-Complete-FAANG-Preparation#262]
👋 Hi @AkashSingh3031 ,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Learn + Collaborate` repo. This means that you would like to teach students, step by step, how to build this project as well as invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a `Learn + Collaborate` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

Your repo is already in great shape! I am very impressed with it's current state so there won't be too much I will recommend for updates/changes 😅 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you :octocat: 

## Issues
- [x] https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/issues/263
- [x] https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/issues/264
- [x] https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/issues/265

**Comment by AkashSingh3031** [comment]
Thank You @ericdrosado Sir!

I am ready to work on this repo under your guidance.

**Comment by AkashSingh3031** [comment]
@ericdrosado Sir!

Check the repo
If any changes are required then comment here

**Comment by ericdrosado** [comment]
@AkashSingh3031 you are all set for now. I will send you a message next week on next steps to submit your repository! 🎉

**Comment by AkashSingh3031** [comment]
> @AkashSingh3031 you are all set for now. I will send you a message next week on next steps to submit your repository! 🎉

Ok, Sir
